"""Initial schema for all models

Revision ID: a21ba0cd9e58
Revises: ef940c1af866
Create Date: 2025-05-18 16:36:01.221429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21ba0cd9e58'
down_revision = 'ef940c1af866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ac_unit', schema=None) as batch_op:
        batch_op.alter_column('working_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Boolean(),
               postgresql_using='CASE WHEN working_status = \'Working\' THEN true ELSE false END')

    with op.batch_alter_table('alarm_extension', schema=None) as batch_op:
        batch_op.alter_column('ac_main_failure',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('dc_low_voltages',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('rectifier_failure',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('general_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('exchange_lic', sa.String(length=50), nullable=True))
        batch_op.drop_column('site_lic')
        batch_op.drop_column('site_name')
        batch_op.drop_column('site_type')

    with op.batch_alter_table('power_information', schema=None) as batch_op:
        batch_op.alter_column('working_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('grounding_of_rectifier',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('power_information', schema=None) as batch_op:
        batch_op.alter_column('grounding_of_rectifier',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('working_status',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('general_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_type', sa.VARCHAR(length=50), server_default=sa.text("'Unknown'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('site_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('site_lic', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('exchange_lic')
        batch_op.drop_column('exchange_name')

    with op.batch_alter_table('alarm_extension', schema=None) as batch_op:
        batch_op.alter_column('rectifier_failure',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('dc_low_voltages',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('ac_main_failure',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('ac_unit', schema=None) as batch_op:
        batch_op.alter_column('working_status',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
