"""Add site_status to general_information

Revision ID: ef940c1af866
Revises: 
Create Date: 2025-05-18 16:04:52.572136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef940c1af866'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ac_unit', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('working_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('ac_make',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('fault_nature_of_ac_unit',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('alarm_extension', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ac_main_failure',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('dc_low_voltages',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('rectifier_failure',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('battery_bank', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('make_of_battery',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('building_information', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('building_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('colocation_information', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('dg', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('installed_dg',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('engine_make',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('dg_starting_battery',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('ats_capacity',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('name_of_faulty_ats_parts',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('earthing', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('fire_extinguisher', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('type_of_gas',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('general_information', schema=None) as batch_op:
        site_type = db.Column(db.String(50), nullable=False, default='Exchange')
        batch_op.add_column(sa.Column('site_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('site_lic', sa.String(length=50), nullable=True))
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('domain',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('flc',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('site_category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('tower_available',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_column('exchange_name')
        batch_op.drop_column('exchange_lic')

    with op.batch_alter_table('installed_solar_information', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('make_of_pv_panels',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('charge_controller_make',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('charge_controller_capacity')
        batch_op.drop_column('no_of_inverters')
        batch_op.drop_column('roof_top_ground')
        batch_op.drop_column('on_grid_hybrid')
        batch_op.drop_column('inverter_capacity')
        batch_op.drop_column('inverter_make')
        batch_op.drop_column('no_of_charge_controllers')

    with op.batch_alter_table('pmr_information', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('power_information', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('wapda_ref_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('transformer_capacity',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('transformer_earthing',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('working_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('make_of_rectifier',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('grounding_of_rectifier',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('spd_model',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('tower', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tower_type_height',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tower', schema=None) as batch_op:
        batch_op.alter_column('tower_type_height',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('power_information', schema=None) as batch_op:
        batch_op.alter_column('spd_model',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('grounding_of_rectifier',
               existing_type=sa.String(length=10),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('make_of_rectifier',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('working_status',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('transformer_earthing',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('transformer_capacity',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('wapda_ref_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pmr_information', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('installed_solar_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_of_charge_controllers', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('inverter_make', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('inverter_capacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('on_grid_hybrid', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('roof_top_ground', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('no_of_inverters', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('charge_controller_capacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('charge_controller_make',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('make_of_pv_panels',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('general_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange_lic', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('exchange_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('tower_available',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
        batch_op.alter_column('site_category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('flc',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('domain',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('site_lic')
        batch_op.drop_column('site_name')
        batch_op.drop_column('site_type')

    with op.batch_alter_table('fire_extinguisher', schema=None) as batch_op:
        batch_op.alter_column('type_of_gas',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('earthing', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('dg', schema=None) as batch_op:
        batch_op.alter_column('name_of_faulty_ats_parts',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('ats_capacity',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('dg_starting_battery',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('engine_make',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('installed_dg',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('colocation_information', schema=None) as batch_op:
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('building_information', schema=None) as batch_op:
        batch_op.alter_column('building_status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('battery_bank', schema=None) as batch_op:
        batch_op.alter_column('make_of_battery',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('alarm_extension', schema=None) as batch_op:
        batch_op.alter_column('rectifier_failure',
               existing_type=sa.String(length=10),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('dc_low_voltages',
               existing_type=sa.String(length=10),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('ac_main_failure',
               existing_type=sa.String(length=10),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('ac_unit', schema=None) as batch_op:
        batch_op.alter_column('fault_nature_of_ac_unit',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('ac_make',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('working_status',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('general_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
